sudo: false
language: cpp
dist: bionic
os: linux

# NB. boost installation/vars copied from main rippled travis config

env:
  global:
    - LLVM_VERSION=6.0.0
    - CACHE_DIR=${TRAVIS_HOME}/_cache
    - BOOST_ROOT=${CACHE_DIR}/boost_1_71_0
    # this is NOT used by linux container based builds (which already have boost installed)
    - BOOST_URL='https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2'
    # Alternate dowload location
    - BOOST_URL2='https://downloads.sourceforge.net/project/boost/boost/1.71.0/boost_1_71_0.tar.bz2?r=&amp;ts=1594393912&amp;use_mirror=newcontinuum'
    # Travis downloader doesn't seem to have updated certs. Using this option
    # introduces obvious security risks, but they're Travis's risks.
    # Note that this option is only used if the "normal" build fails.
    - BOOST_WGET_OPTIONS='--no-check-certificate'

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - gcc-8
      - g++-8
      - libssl-dev
      - cmake

matrix:
  include:
    - compiler: gcc-8
    env:
      - CC=/usr/bin/gcc-8
      - CXX=/usr/bin/g++-8
      - GCC_VER=8
      - BUILD_TYPE=Debug
      - PARALLEL_TESTS='false'
      - CMAKE_EXTRA_ARGS='-Werr=ON -Dcoverage=ON'
      - PATH=$PWD/cmake/bin:$PATH
      - APP=ripplelibppdemo

cache:
  timeout: 10
  directories:
    - $CACHE_DIR

install:
  - travis_wait ${MAX_TIME_MIN} ./scripts/install_boost.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBoost_DEBUG=ON -DBOOST_ROOT=$BOOST_ROOT -DLIBPPDEMO_DOWNLOAD_RIPPLED=ON $CMAKE_EXTRA_ARGS .
  - cmake --build build --config $BUILD_TYPE .

